// Generated by gencpp from file serial_port_ros/serial_data.msg
// DO NOT EDIT!


#ifndef SERIAL_PORT_ROS_MESSAGE_SERIAL_DATA_H
#define SERIAL_PORT_ROS_MESSAGE_SERIAL_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_port_ros
{
template <class ContainerAllocator>
struct serial_data_
{
  typedef serial_data_<ContainerAllocator> Type;

  serial_data_()
    : data(0)  {
    }
  serial_data_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::serial_port_ros::serial_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_port_ros::serial_data_<ContainerAllocator> const> ConstPtr;

}; // struct serial_data_

typedef ::serial_port_ros::serial_data_<std::allocator<void> > serial_data;

typedef boost::shared_ptr< ::serial_port_ros::serial_data > serial_dataPtr;
typedef boost::shared_ptr< ::serial_port_ros::serial_data const> serial_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_port_ros::serial_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_port_ros::serial_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::serial_port_ros::serial_data_<ContainerAllocator1> & lhs, const ::serial_port_ros::serial_data_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::serial_port_ros::serial_data_<ContainerAllocator1> & lhs, const ::serial_port_ros::serial_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace serial_port_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::serial_port_ros::serial_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_port_ros::serial_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_port_ros::serial_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_port_ros::serial_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port_ros::serial_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_port_ros::serial_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_port_ros::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1bf77f25acecdedba0e224b162199717";
  }

  static const char* value(const ::serial_port_ros::serial_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1bf77f25acecdedbULL;
  static const uint64_t static_value2 = 0xa0e224b162199717ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_port_ros::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_port_ros/serial_data";
  }

  static const char* value(const ::serial_port_ros::serial_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_port_ros::serial_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char data\n"
;
  }

  static const char* value(const ::serial_port_ros::serial_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_port_ros::serial_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_port_ros::serial_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_port_ros::serial_data_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_PORT_ROS_MESSAGE_SERIAL_DATA_H
